import { z } from "zod";

import { paginationParamsSchema } from "@/lib/pagination";

const id = (message: string) => z.string().min(1, message);

const name = z.string().trim().min(1, "Name is required").max(160);

export const GENDERS = ["MALE", "FEMALE", "OTHER"] as const;

// Deliberately loose — there's no existing phone convention in the app, and
// field staff type numbers in many shapes (+243 ..., 0xx xxx, (0)...). Only
// the character set and a sane length are enforced.
const mobile = z
  .string()
  .trim()
  .min(6, "Mobile number is too short")
  .max(20, "Mobile number is too long")
  .regex(/^[0-9+()\-\s]+$/, "Mobile number may only contain digits, spaces, +, - and ()");

// One Contact<->Center link. `centerId` is the Center (the Center model).
export const contactCenterSchema = z.object({
  centerId: id("Select a center"),
  roleAtCenterId: id("Select a role at this center"),
});
export type ContactCenterInput = z.infer<typeof contactCenterSchema>;

const centers = z.array(contactCenterSchema).superRefine((items, ctx) => {
  const seen = new Set<string>();
  items.forEach((item, index) => {
    if (seen.has(item.centerId)) {
      ctx.addIssue({
        code: "custom",
        path: [index, "centerId"],
        message: "This center is already associated with the contact.",
      });
    }
    seen.add(item.centerId);
  });
});

// No `code` field on purpose — Contact codes are generated by the backend and
// never accepted from input (zod strips unknown keys, so a submitted `code`
// is discarded rather than rejected).
export const createContactSchema = z.object({
  name,
  contactTypeId: id("Contact type is required"),
  gender: z.enum(GENDERS).nullish(),
  mobile: mobile.nullish(),
  specializationId: id("Specialization / department is required"),
  territoryId: id("Territory is required"),
  centers,
});
export type CreateContactInput = z.infer<typeof createContactSchema>;

export const updateContactSchema = createContactSchema.extend({
  id: id("Missing contact id"),
  // Absent means "leave as-is"; present is an explicit set, same convention
  // as UpdateCenterInput.
  status: z.enum(["ACTIVE", "INACTIVE"]).optional(),
});
export type UpdateContactInput = z.infer<typeof updateContactSchema>;

export const setContactStatusSchema = z.object({
  id: id("Missing contact id"),
  status: z.enum(["ACTIVE", "INACTIVE"]),
});

// Create-or-select comboboxes: typing a value that doesn't exist yet
// creates it as a configurable lookup row.
export const LOOKUP_KINDS = ["contactType", "specialization", "centerRole"] as const;
export type LookupKind = (typeof LOOKUP_KINDS)[number];

export const createLookupSchema = z.object({
  kind: z.enum(LOOKUP_KINDS),
  name: z.string().trim().min(1, "Name is required").max(120, "Name is too long"),
});
export type CreateLookupInput = z.infer<typeof createLookupSchema>;

// A Center as offered by the association editor's picker. `typeName` is the
// existing Center Type (CenterType) name.
export type CenterOption = { id: string; code: string; name: string; typeName: string };

export const contactFiltersSchema = z
  .object({
    q: z.string().trim().optional(),
    contactTypeId: z.string().optional(),
    specializationId: z.string().optional(),
    // Center Type = the existing CenterType, matched through the Contact's
    // associated Centers.
    centerTypeId: z.string().optional(),
    territoryId: z.string().optional(),
    status: z.enum(["ACTIVE", "INACTIVE"]).optional(),
  })
  .merge(paginationParamsSchema);
export type ContactFilters = z.infer<typeof contactFiltersSchema>;
